#!/usr/bin/env bash

(cd ../src
echo ""
echo "<ul>"
for f in *.py; do
  g=${f%.*}.html
  echo "<li><a href=\"$g\">$f</a>:"
  gawk 'gsub(/"""/,"") { print $0; exit}' $f
  echo "<br></li>"
done
echo "</ul>"
echo ""
)
